### ISSUE TITLE
Material Design checklist

### ISSUE THREAD

**Issue by royarzun** [royarzun/XYZReader#1]
**Lyla says:**
_This app is starting to shape up but it feels a bit off in quite a few places. I can't put finger on it but it feels odd._
- [x] App properly specifies elevations for app bars, FABs, and other elements specified in the Material Design specification.
- [x] App provides a Floating Action Button for the most common action(s).
- [x] App has a consistent color theme defined in styles.xml. Color theme does not impact usability of the app.
